// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flume_msg.proto

package com.iscas;

public final class FlumeMsgListProtos {
  private FlumeMsgListProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeadersOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string topic = 1;
    /**
     * <code>optional string topic = 1;</code>
     */
    boolean hasTopic();
    /**
     * <code>optional string topic = 1;</code>
     */
    java.lang.String getTopic();
    /**
     * <code>optional string topic = 1;</code>
     */
    com.google.protobuf.ByteString
        getTopicBytes();
  }
  /**
   * Protobuf type {@code youzhen.Headers}
   */
  public static final class Headers extends
      com.google.protobuf.GeneratedMessage
      implements HeadersOrBuilder {
    // Use Headers.newBuilder() to construct.
    private Headers(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Headers(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Headers defaultInstance;
    public static Headers getDefaultInstance() {
      return defaultInstance;
    }

    public Headers getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Headers(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              topic_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iscas.FlumeMsgListProtos.internal_static_youzhen_Headers_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iscas.FlumeMsgListProtos.internal_static_youzhen_Headers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iscas.FlumeMsgListProtos.Headers.class, com.iscas.FlumeMsgListProtos.Headers.Builder.class);
    }

    public static com.google.protobuf.Parser<Headers> PARSER =
        new com.google.protobuf.AbstractParser<Headers>() {
      public Headers parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Headers(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Headers> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string topic = 1;
    public static final int TOPIC_FIELD_NUMBER = 1;
    private java.lang.Object topic_;
    /**
     * <code>optional string topic = 1;</code>
     */
    public boolean hasTopic() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string topic = 1;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          topic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string topic = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      topic_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTopicBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTopicBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.iscas.FlumeMsgListProtos.Headers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iscas.FlumeMsgListProtos.Headers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iscas.FlumeMsgListProtos.Headers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iscas.FlumeMsgListProtos.Headers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iscas.FlumeMsgListProtos.Headers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.iscas.FlumeMsgListProtos.Headers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.iscas.FlumeMsgListProtos.Headers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.iscas.FlumeMsgListProtos.Headers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.iscas.FlumeMsgListProtos.Headers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.iscas.FlumeMsgListProtos.Headers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.iscas.FlumeMsgListProtos.Headers prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code youzhen.Headers}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.iscas.FlumeMsgListProtos.HeadersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iscas.FlumeMsgListProtos.internal_static_youzhen_Headers_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iscas.FlumeMsgListProtos.internal_static_youzhen_Headers_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iscas.FlumeMsgListProtos.Headers.class, com.iscas.FlumeMsgListProtos.Headers.Builder.class);
      }

      // Construct using com.iscas.FlumeMsgListProtos.Headers.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        topic_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.iscas.FlumeMsgListProtos.internal_static_youzhen_Headers_descriptor;
      }

      public com.iscas.FlumeMsgListProtos.Headers getDefaultInstanceForType() {
        return com.iscas.FlumeMsgListProtos.Headers.getDefaultInstance();
      }

      public com.iscas.FlumeMsgListProtos.Headers build() {
        com.iscas.FlumeMsgListProtos.Headers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.iscas.FlumeMsgListProtos.Headers buildPartial() {
        com.iscas.FlumeMsgListProtos.Headers result = new com.iscas.FlumeMsgListProtos.Headers(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.topic_ = topic_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iscas.FlumeMsgListProtos.Headers) {
          return mergeFrom((com.iscas.FlumeMsgListProtos.Headers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iscas.FlumeMsgListProtos.Headers other) {
        if (other == com.iscas.FlumeMsgListProtos.Headers.getDefaultInstance()) return this;
        if (other.hasTopic()) {
          bitField0_ |= 0x00000001;
          topic_ = other.topic_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.iscas.FlumeMsgListProtos.Headers parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iscas.FlumeMsgListProtos.Headers) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string topic = 1;
      private java.lang.Object topic_ = "";
      /**
       * <code>optional string topic = 1;</code>
       */
      public boolean hasTopic() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string topic = 1;</code>
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string topic = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string topic = 1;</code>
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string topic = 1;</code>
       */
      public Builder clearTopic() {
        bitField0_ = (bitField0_ & ~0x00000001);
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string topic = 1;</code>
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:youzhen.Headers)
    }

    static {
      defaultInstance = new Headers(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:youzhen.Headers)
  }

  public interface FlumeMsgListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;
    /**
     * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
     */
    java.util.List<com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg> 
        getMsgList();
    /**
     * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
     */
    com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg getMsg(int index);
    /**
     * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
     */
    int getMsgCount();
    /**
     * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
     */
    java.util.List<? extends com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsgOrBuilder> 
        getMsgOrBuilderList();
    /**
     * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
     */
    com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsgOrBuilder getMsgOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code youzhen.FlumeMsgList}
   */
  public static final class FlumeMsgList extends
      com.google.protobuf.GeneratedMessage
      implements FlumeMsgListOrBuilder {
    // Use FlumeMsgList.newBuilder() to construct.
    private FlumeMsgList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FlumeMsgList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FlumeMsgList defaultInstance;
    public static FlumeMsgList getDefaultInstance() {
      return defaultInstance;
    }

    public FlumeMsgList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FlumeMsgList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                msg_ = new java.util.ArrayList<com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg>();
                mutable_bitField0_ |= 0x00000001;
              }
              msg_.add(input.readMessage(com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          msg_ = java.util.Collections.unmodifiableList(msg_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iscas.FlumeMsgListProtos.internal_static_youzhen_FlumeMsgList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iscas.FlumeMsgListProtos.internal_static_youzhen_FlumeMsgList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iscas.FlumeMsgListProtos.FlumeMsgList.class, com.iscas.FlumeMsgListProtos.FlumeMsgList.Builder.class);
    }

    public static com.google.protobuf.Parser<FlumeMsgList> PARSER =
        new com.google.protobuf.AbstractParser<FlumeMsgList>() {
      public FlumeMsgList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FlumeMsgList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FlumeMsgList> getParserForType() {
      return PARSER;
    }

    public interface FlumeMsgOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required .youzhen.Headers headers = 1;
      /**
       * <code>required .youzhen.Headers headers = 1;</code>
       */
      boolean hasHeaders();
      /**
       * <code>required .youzhen.Headers headers = 1;</code>
       */
      com.iscas.FlumeMsgListProtos.Headers getHeaders();
      /**
       * <code>required .youzhen.Headers headers = 1;</code>
       */
      com.iscas.FlumeMsgListProtos.HeadersOrBuilder getHeadersOrBuilder();

      // required bytes body = 2;
      /**
       * <code>required bytes body = 2;</code>
       */
      boolean hasBody();
      /**
       * <code>required bytes body = 2;</code>
       */
      com.google.protobuf.ByteString getBody();
    }
    /**
     * Protobuf type {@code youzhen.FlumeMsgList.FlumeMsg}
     */
    public static final class FlumeMsg extends
        com.google.protobuf.GeneratedMessage
        implements FlumeMsgOrBuilder {
      // Use FlumeMsg.newBuilder() to construct.
      private FlumeMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private FlumeMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final FlumeMsg defaultInstance;
      public static FlumeMsg getDefaultInstance() {
        return defaultInstance;
      }

      public FlumeMsg getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private FlumeMsg(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.iscas.FlumeMsgListProtos.Headers.Builder subBuilder = null;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                  subBuilder = headers_.toBuilder();
                }
                headers_ = input.readMessage(com.iscas.FlumeMsgListProtos.Headers.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(headers_);
                  headers_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000001;
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                body_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iscas.FlumeMsgListProtos.internal_static_youzhen_FlumeMsgList_FlumeMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iscas.FlumeMsgListProtos.internal_static_youzhen_FlumeMsgList_FlumeMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.class, com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.Builder.class);
      }

      public static com.google.protobuf.Parser<FlumeMsg> PARSER =
          new com.google.protobuf.AbstractParser<FlumeMsg>() {
        public FlumeMsg parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new FlumeMsg(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<FlumeMsg> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required .youzhen.Headers headers = 1;
      public static final int HEADERS_FIELD_NUMBER = 1;
      private com.iscas.FlumeMsgListProtos.Headers headers_;
      /**
       * <code>required .youzhen.Headers headers = 1;</code>
       */
      public boolean hasHeaders() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .youzhen.Headers headers = 1;</code>
       */
      public com.iscas.FlumeMsgListProtos.Headers getHeaders() {
        return headers_;
      }
      /**
       * <code>required .youzhen.Headers headers = 1;</code>
       */
      public com.iscas.FlumeMsgListProtos.HeadersOrBuilder getHeadersOrBuilder() {
        return headers_;
      }

      // required bytes body = 2;
      public static final int BODY_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString body_;
      /**
       * <code>required bytes body = 2;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes body = 2;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }

      private void initFields() {
        headers_ = com.iscas.FlumeMsgListProtos.Headers.getDefaultInstance();
        body_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasHeaders()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasBody()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeMessage(1, headers_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, body_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, headers_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, body_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code youzhen.FlumeMsgList.FlumeMsg}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsgOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.iscas.FlumeMsgListProtos.internal_static_youzhen_FlumeMsgList_FlumeMsg_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.iscas.FlumeMsgListProtos.internal_static_youzhen_FlumeMsgList_FlumeMsg_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.class, com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.Builder.class);
        }

        // Construct using com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getHeadersFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          if (headersBuilder_ == null) {
            headers_ = com.iscas.FlumeMsgListProtos.Headers.getDefaultInstance();
          } else {
            headersBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          body_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.iscas.FlumeMsgListProtos.internal_static_youzhen_FlumeMsgList_FlumeMsg_descriptor;
        }

        public com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg getDefaultInstanceForType() {
          return com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.getDefaultInstance();
        }

        public com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg build() {
          com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg buildPartial() {
          com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg result = new com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          if (headersBuilder_ == null) {
            result.headers_ = headers_;
          } else {
            result.headers_ = headersBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.body_ = body_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg) {
            return mergeFrom((com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg other) {
          if (other == com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.getDefaultInstance()) return this;
          if (other.hasHeaders()) {
            mergeHeaders(other.getHeaders());
          }
          if (other.hasBody()) {
            setBody(other.getBody());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasHeaders()) {
            
            return false;
          }
          if (!hasBody()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required .youzhen.Headers headers = 1;
        private com.iscas.FlumeMsgListProtos.Headers headers_ = com.iscas.FlumeMsgListProtos.Headers.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            com.iscas.FlumeMsgListProtos.Headers, com.iscas.FlumeMsgListProtos.Headers.Builder, com.iscas.FlumeMsgListProtos.HeadersOrBuilder> headersBuilder_;
        /**
         * <code>required .youzhen.Headers headers = 1;</code>
         */
        public boolean hasHeaders() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .youzhen.Headers headers = 1;</code>
         */
        public com.iscas.FlumeMsgListProtos.Headers getHeaders() {
          if (headersBuilder_ == null) {
            return headers_;
          } else {
            return headersBuilder_.getMessage();
          }
        }
        /**
         * <code>required .youzhen.Headers headers = 1;</code>
         */
        public Builder setHeaders(com.iscas.FlumeMsgListProtos.Headers value) {
          if (headersBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            headers_ = value;
            onChanged();
          } else {
            headersBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>required .youzhen.Headers headers = 1;</code>
         */
        public Builder setHeaders(
            com.iscas.FlumeMsgListProtos.Headers.Builder builderForValue) {
          if (headersBuilder_ == null) {
            headers_ = builderForValue.build();
            onChanged();
          } else {
            headersBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>required .youzhen.Headers headers = 1;</code>
         */
        public Builder mergeHeaders(com.iscas.FlumeMsgListProtos.Headers value) {
          if (headersBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001) &&
                headers_ != com.iscas.FlumeMsgListProtos.Headers.getDefaultInstance()) {
              headers_ =
                com.iscas.FlumeMsgListProtos.Headers.newBuilder(headers_).mergeFrom(value).buildPartial();
            } else {
              headers_ = value;
            }
            onChanged();
          } else {
            headersBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>required .youzhen.Headers headers = 1;</code>
         */
        public Builder clearHeaders() {
          if (headersBuilder_ == null) {
            headers_ = com.iscas.FlumeMsgListProtos.Headers.getDefaultInstance();
            onChanged();
          } else {
            headersBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        /**
         * <code>required .youzhen.Headers headers = 1;</code>
         */
        public com.iscas.FlumeMsgListProtos.Headers.Builder getHeadersBuilder() {
          bitField0_ |= 0x00000001;
          onChanged();
          return getHeadersFieldBuilder().getBuilder();
        }
        /**
         * <code>required .youzhen.Headers headers = 1;</code>
         */
        public com.iscas.FlumeMsgListProtos.HeadersOrBuilder getHeadersOrBuilder() {
          if (headersBuilder_ != null) {
            return headersBuilder_.getMessageOrBuilder();
          } else {
            return headers_;
          }
        }
        /**
         * <code>required .youzhen.Headers headers = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            com.iscas.FlumeMsgListProtos.Headers, com.iscas.FlumeMsgListProtos.Headers.Builder, com.iscas.FlumeMsgListProtos.HeadersOrBuilder> 
            getHeadersFieldBuilder() {
          if (headersBuilder_ == null) {
            headersBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                com.iscas.FlumeMsgListProtos.Headers, com.iscas.FlumeMsgListProtos.Headers.Builder, com.iscas.FlumeMsgListProtos.HeadersOrBuilder>(
                    headers_,
                    getParentForChildren(),
                    isClean());
            headers_ = null;
          }
          return headersBuilder_;
        }

        // required bytes body = 2;
        private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes body = 2;</code>
         */
        public boolean hasBody() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes body = 2;</code>
         */
        public com.google.protobuf.ByteString getBody() {
          return body_;
        }
        /**
         * <code>required bytes body = 2;</code>
         */
        public Builder setBody(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          body_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes body = 2;</code>
         */
        public Builder clearBody() {
          bitField0_ = (bitField0_ & ~0x00000002);
          body_ = getDefaultInstance().getBody();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:youzhen.FlumeMsgList.FlumeMsg)
      }

      static {
        defaultInstance = new FlumeMsg(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:youzhen.FlumeMsgList.FlumeMsg)
    }

    // repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;
    public static final int MSG_FIELD_NUMBER = 1;
    private java.util.List<com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg> msg_;
    /**
     * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
     */
    public java.util.List<com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg> getMsgList() {
      return msg_;
    }
    /**
     * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
     */
    public java.util.List<? extends com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsgOrBuilder> 
        getMsgOrBuilderList() {
      return msg_;
    }
    /**
     * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
     */
    public int getMsgCount() {
      return msg_.size();
    }
    /**
     * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
     */
    public com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg getMsg(int index) {
      return msg_.get(index);
    }
    /**
     * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
     */
    public com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsgOrBuilder getMsgOrBuilder(
        int index) {
      return msg_.get(index);
    }

    private void initFields() {
      msg_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getMsgCount(); i++) {
        if (!getMsg(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < msg_.size(); i++) {
        output.writeMessage(1, msg_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < msg_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, msg_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.iscas.FlumeMsgListProtos.FlumeMsgList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iscas.FlumeMsgListProtos.FlumeMsgList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iscas.FlumeMsgListProtos.FlumeMsgList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iscas.FlumeMsgListProtos.FlumeMsgList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iscas.FlumeMsgListProtos.FlumeMsgList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.iscas.FlumeMsgListProtos.FlumeMsgList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.iscas.FlumeMsgListProtos.FlumeMsgList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.iscas.FlumeMsgListProtos.FlumeMsgList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.iscas.FlumeMsgListProtos.FlumeMsgList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.iscas.FlumeMsgListProtos.FlumeMsgList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.iscas.FlumeMsgListProtos.FlumeMsgList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code youzhen.FlumeMsgList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.iscas.FlumeMsgListProtos.FlumeMsgListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iscas.FlumeMsgListProtos.internal_static_youzhen_FlumeMsgList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iscas.FlumeMsgListProtos.internal_static_youzhen_FlumeMsgList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iscas.FlumeMsgListProtos.FlumeMsgList.class, com.iscas.FlumeMsgListProtos.FlumeMsgList.Builder.class);
      }

      // Construct using com.iscas.FlumeMsgListProtos.FlumeMsgList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (msgBuilder_ == null) {
          msg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          msgBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.iscas.FlumeMsgListProtos.internal_static_youzhen_FlumeMsgList_descriptor;
      }

      public com.iscas.FlumeMsgListProtos.FlumeMsgList getDefaultInstanceForType() {
        return com.iscas.FlumeMsgListProtos.FlumeMsgList.getDefaultInstance();
      }

      public com.iscas.FlumeMsgListProtos.FlumeMsgList build() {
        com.iscas.FlumeMsgListProtos.FlumeMsgList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.iscas.FlumeMsgListProtos.FlumeMsgList buildPartial() {
        com.iscas.FlumeMsgListProtos.FlumeMsgList result = new com.iscas.FlumeMsgListProtos.FlumeMsgList(this);
        int from_bitField0_ = bitField0_;
        if (msgBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            msg_ = java.util.Collections.unmodifiableList(msg_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iscas.FlumeMsgListProtos.FlumeMsgList) {
          return mergeFrom((com.iscas.FlumeMsgListProtos.FlumeMsgList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iscas.FlumeMsgListProtos.FlumeMsgList other) {
        if (other == com.iscas.FlumeMsgListProtos.FlumeMsgList.getDefaultInstance()) return this;
        if (msgBuilder_ == null) {
          if (!other.msg_.isEmpty()) {
            if (msg_.isEmpty()) {
              msg_ = other.msg_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMsgIsMutable();
              msg_.addAll(other.msg_);
            }
            onChanged();
          }
        } else {
          if (!other.msg_.isEmpty()) {
            if (msgBuilder_.isEmpty()) {
              msgBuilder_.dispose();
              msgBuilder_ = null;
              msg_ = other.msg_;
              bitField0_ = (bitField0_ & ~0x00000001);
              msgBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMsgFieldBuilder() : null;
            } else {
              msgBuilder_.addAllMessages(other.msg_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMsgCount(); i++) {
          if (!getMsg(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.iscas.FlumeMsgListProtos.FlumeMsgList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iscas.FlumeMsgListProtos.FlumeMsgList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;
      private java.util.List<com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg> msg_ =
        java.util.Collections.emptyList();
      private void ensureMsgIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          msg_ = new java.util.ArrayList<com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg>(msg_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg, com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.Builder, com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsgOrBuilder> msgBuilder_;

      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public java.util.List<com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg> getMsgList() {
        if (msgBuilder_ == null) {
          return java.util.Collections.unmodifiableList(msg_);
        } else {
          return msgBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public int getMsgCount() {
        if (msgBuilder_ == null) {
          return msg_.size();
        } else {
          return msgBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg getMsg(int index) {
        if (msgBuilder_ == null) {
          return msg_.get(index);
        } else {
          return msgBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public Builder setMsg(
          int index, com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgIsMutable();
          msg_.set(index, value);
          onChanged();
        } else {
          msgBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public Builder setMsg(
          int index, com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.set(index, builderForValue.build());
          onChanged();
        } else {
          msgBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public Builder addMsg(com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgIsMutable();
          msg_.add(value);
          onChanged();
        } else {
          msgBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public Builder addMsg(
          int index, com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgIsMutable();
          msg_.add(index, value);
          onChanged();
        } else {
          msgBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public Builder addMsg(
          com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.add(builderForValue.build());
          onChanged();
        } else {
          msgBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public Builder addMsg(
          int index, com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.add(index, builderForValue.build());
          onChanged();
        } else {
          msgBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public Builder addAllMsg(
          java.lang.Iterable<? extends com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg> values) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          super.addAll(values, msg_);
          onChanged();
        } else {
          msgBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          msgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public Builder removeMsg(int index) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.remove(index);
          onChanged();
        } else {
          msgBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.Builder getMsgBuilder(
          int index) {
        return getMsgFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsgOrBuilder getMsgOrBuilder(
          int index) {
        if (msgBuilder_ == null) {
          return msg_.get(index);  } else {
          return msgBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public java.util.List<? extends com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsgOrBuilder> 
           getMsgOrBuilderList() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(msg_);
        }
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.Builder addMsgBuilder() {
        return getMsgFieldBuilder().addBuilder(
            com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.Builder addMsgBuilder(
          int index) {
        return getMsgFieldBuilder().addBuilder(
            index, com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .youzhen.FlumeMsgList.FlumeMsg msg = 1;</code>
       */
      public java.util.List<com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.Builder> 
           getMsgBuilderList() {
        return getMsgFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg, com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.Builder, com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsgOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg, com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsg.Builder, com.iscas.FlumeMsgListProtos.FlumeMsgList.FlumeMsgOrBuilder>(
                  msg_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:youzhen.FlumeMsgList)
    }

    static {
      defaultInstance = new FlumeMsgList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:youzhen.FlumeMsgList)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_youzhen_Headers_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_youzhen_Headers_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_youzhen_FlumeMsgList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_youzhen_FlumeMsgList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_youzhen_FlumeMsgList_FlumeMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_youzhen_FlumeMsgList_FlumeMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017flume_msg.proto\022\007youzhen\"\030\n\007Headers\022\r\n" +
      "\005topic\030\001 \001(\t\"x\n\014FlumeMsgList\022+\n\003msg\030\001 \003(" +
      "\0132\036.youzhen.FlumeMsgList.FlumeMsg\032;\n\010Flu" +
      "meMsg\022!\n\007headers\030\001 \002(\0132\020.youzhen.Headers" +
      "\022\014\n\004body\030\002 \002(\014B\037\n\tcom.iscasB\022FlumeMsgLis" +
      "tProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_youzhen_Headers_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_youzhen_Headers_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_youzhen_Headers_descriptor,
              new java.lang.String[] { "Topic", });
          internal_static_youzhen_FlumeMsgList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_youzhen_FlumeMsgList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_youzhen_FlumeMsgList_descriptor,
              new java.lang.String[] { "Msg", });
          internal_static_youzhen_FlumeMsgList_FlumeMsg_descriptor =
            internal_static_youzhen_FlumeMsgList_descriptor.getNestedTypes().get(0);
          internal_static_youzhen_FlumeMsgList_FlumeMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_youzhen_FlumeMsgList_FlumeMsg_descriptor,
              new java.lang.String[] { "Headers", "Body", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
