# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exp.proto',
  package='youzhen',
  serialized_pb='\n\texp.proto\x12\x07youzhen\"\xbf\x01\n\x07\x45xpInfo\x12\x1a\n\x12logisticproviderid\x18\x01 \x02(\t\x12\x0e\n\x06mailno\x18\x02 \x02(\t\x12\x10\n\x08mailtype\x18\x03 \x02(\t\x12\x0e\n\x06weight\x18\x04 \x02(\t\x12\x13\n\x0bsencitycode\x18\x05 \x02(\t\x12\x13\n\x0breccitycode\x18\x06 \x02(\t\x12\x13\n\x0bsenareacode\x18\x07 \x02(\t\x12\x13\n\x0brecareacode\x18\x08 \x02(\t\x12\x12\n\ninserttime\x18\t \x02(\x01\"\x88\x01\n\x07\x45xpSend\x12\x0f\n\x07senname\x18\x01 \x02(\t\x12\x11\n\tsenmobile\x18\x02 \x02(\t\x12\x10\n\x08senphone\x18\x03 \x02(\t\x12\x0f\n\x07senprov\x18\x04 \x02(\t\x12\x0f\n\x07sencity\x18\x05 \x02(\t\x12\x11\n\tsencounty\x18\x06 \x02(\t\x12\x12\n\nsenaddress\x18\x07 \x02(\t\"\x88\x01\n\x07\x45xpRecv\x12\x0f\n\x07recname\x18\x01 \x02(\t\x12\x11\n\trecmobile\x18\x02 \x02(\t\x12\x10\n\x08recphone\x18\x03 \x02(\t\x12\x0f\n\x07recprov\x18\x04 \x02(\t\x12\x0f\n\x07reccity\x18\x05 \x02(\t\x12\x11\n\treccounty\x18\x06 \x02(\t\x12\x12\n\nrecaddress\x18\x07 \x02(\t\"w\n\x06\x45xpPkg\x12\x16\n\x0etypeofcontents\x18\x01 \x02(\t\x12\x16\n\x0enameofcoutents\x18\x02 \x02(\t\x12\x10\n\x08mailcode\x18\x03 \x02(\t\x12\x13\n\x0brecdatetime\x18\x04 \x02(\t\x12\x16\n\x0einsurancevalue\x18\x05 \x02(\t\"\x83\x01\n\x03\x45xp\x12\x1e\n\x04info\x18\x01 \x02(\x0b\x32\x10.youzhen.ExpInfo\x12\x1e\n\x04send\x18\x02 \x02(\x0b\x32\x10.youzhen.ExpSend\x12\x1e\n\x04recv\x18\x03 \x02(\x0b\x32\x10.youzhen.ExpRecv\x12\x1c\n\x03pkg\x18\x04 \x02(\x0b\x32\x0f.youzhen.ExpPkg\"M\n\x06\x45xpMsg\x12\n\n\x02id\x18\x01 \x02(\t\x12\x1a\n\x04\x64\x61ta\x18\x02 \x02(\x0b\x32\x0c.youzhen.Exp\x12\x0c\n\x04type\x18\x03 \x02(\t\x12\r\n\x05usage\x18\x04 \x02(\t')




_EXPINFO = _descriptor.Descriptor(
  name='ExpInfo',
  full_name='youzhen.ExpInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logisticproviderid', full_name='youzhen.ExpInfo.logisticproviderid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mailno', full_name='youzhen.ExpInfo.mailno', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mailtype', full_name='youzhen.ExpInfo.mailtype', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='youzhen.ExpInfo.weight', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sencitycode', full_name='youzhen.ExpInfo.sencitycode', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reccitycode', full_name='youzhen.ExpInfo.reccitycode', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='senareacode', full_name='youzhen.ExpInfo.senareacode', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recareacode', full_name='youzhen.ExpInfo.recareacode', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inserttime', full_name='youzhen.ExpInfo.inserttime', index=8,
      number=9, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=214,
)


_EXPSEND = _descriptor.Descriptor(
  name='ExpSend',
  full_name='youzhen.ExpSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='senname', full_name='youzhen.ExpSend.senname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='senmobile', full_name='youzhen.ExpSend.senmobile', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='senphone', full_name='youzhen.ExpSend.senphone', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='senprov', full_name='youzhen.ExpSend.senprov', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sencity', full_name='youzhen.ExpSend.sencity', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sencounty', full_name='youzhen.ExpSend.sencounty', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='senaddress', full_name='youzhen.ExpSend.senaddress', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=217,
  serialized_end=353,
)


_EXPRECV = _descriptor.Descriptor(
  name='ExpRecv',
  full_name='youzhen.ExpRecv',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recname', full_name='youzhen.ExpRecv.recname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recmobile', full_name='youzhen.ExpRecv.recmobile', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recphone', full_name='youzhen.ExpRecv.recphone', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recprov', full_name='youzhen.ExpRecv.recprov', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reccity', full_name='youzhen.ExpRecv.reccity', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reccounty', full_name='youzhen.ExpRecv.reccounty', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recaddress', full_name='youzhen.ExpRecv.recaddress', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=356,
  serialized_end=492,
)


_EXPPKG = _descriptor.Descriptor(
  name='ExpPkg',
  full_name='youzhen.ExpPkg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='typeofcontents', full_name='youzhen.ExpPkg.typeofcontents', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nameofcoutents', full_name='youzhen.ExpPkg.nameofcoutents', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mailcode', full_name='youzhen.ExpPkg.mailcode', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recdatetime', full_name='youzhen.ExpPkg.recdatetime', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='insurancevalue', full_name='youzhen.ExpPkg.insurancevalue', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=494,
  serialized_end=613,
)


_EXP = _descriptor.Descriptor(
  name='Exp',
  full_name='youzhen.Exp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='youzhen.Exp.info', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='send', full_name='youzhen.Exp.send', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recv', full_name='youzhen.Exp.recv', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pkg', full_name='youzhen.Exp.pkg', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=616,
  serialized_end=747,
)


_EXPMSG = _descriptor.Descriptor(
  name='ExpMsg',
  full_name='youzhen.ExpMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='youzhen.ExpMsg.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='youzhen.ExpMsg.data', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='youzhen.ExpMsg.type', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usage', full_name='youzhen.ExpMsg.usage', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=749,
  serialized_end=826,
)

_EXP.fields_by_name['info'].message_type = _EXPINFO
_EXP.fields_by_name['send'].message_type = _EXPSEND
_EXP.fields_by_name['recv'].message_type = _EXPRECV
_EXP.fields_by_name['pkg'].message_type = _EXPPKG
_EXPMSG.fields_by_name['data'].message_type = _EXP
DESCRIPTOR.message_types_by_name['ExpInfo'] = _EXPINFO
DESCRIPTOR.message_types_by_name['ExpSend'] = _EXPSEND
DESCRIPTOR.message_types_by_name['ExpRecv'] = _EXPRECV
DESCRIPTOR.message_types_by_name['ExpPkg'] = _EXPPKG
DESCRIPTOR.message_types_by_name['Exp'] = _EXP
DESCRIPTOR.message_types_by_name['ExpMsg'] = _EXPMSG

class ExpInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXPINFO

  # @@protoc_insertion_point(class_scope:youzhen.ExpInfo)

class ExpSend(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXPSEND

  # @@protoc_insertion_point(class_scope:youzhen.ExpSend)

class ExpRecv(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXPRECV

  # @@protoc_insertion_point(class_scope:youzhen.ExpRecv)

class ExpPkg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXPPKG

  # @@protoc_insertion_point(class_scope:youzhen.ExpPkg)

class Exp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXP

  # @@protoc_insertion_point(class_scope:youzhen.Exp)

class ExpMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXPMSG

  # @@protoc_insertion_point(class_scope:youzhen.ExpMsg)


# @@protoc_insertion_point(module_scope)
